spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yummy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Caozhihang2370
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5   #初始化大小
      min-idle: 5   #最小值
      max-active: 20    #最大值
      max-wait: 60000   #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      timeBetweenEvictionRunsMillis: 60000    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      minEvictableIdleTimeMillis: 300000    #配置一个连接在池中最小生存的时间
      validationQuery: SELECT 'X'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  #打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20   #最大PSCache连接
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:     # 配置StatFilter
        enabled: true    #默认为false，设置为true启动
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:     #配置StatViewServlet
        url-pattern: "/druid/*"
        allow: 127.0.0.1    #允许那些ip
        login-username: admin
        login-password: 123456
        deny: 192.168.1.102    #禁止那些ip  
        reset-enable: true    #是否可以重置
        enabled: true     #启用